environment:
  matrix:
    - nodejs_version: '14'
    - nodejs_version: '16'
    - nodejs_version: '18'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g pnpm@latest-5
  - pnpm install
matrix:
  fast_finish: true
build: 'off'
version: '{build}'
test_script:
  - node --version
  - npm --version
  - npm test
